### ISSUE TITLE
Reconnect to MQTT broker if connection is lost

### ISSUE THREAD

**Issue by c0ldtech** [kbialek/deye-inverter-mqtt#166]
It seems that there currently is no reconnect mechanism in place if the connection to MQTT broker is lost for whatever reason.

**To Reproduce**
1. have deye-inverter-mqtt container running and working
2. restart the MQTT broker it is connected to

**Expected behavior**
Connection retries should be attempted at regular intervals.

**Actual behaviour**
Error `Unknown MQTT publishing error: Message publish failed: The client is not currently connected.` is seen in the logs and no reconnection attempt is made.

**Software (please complete the following information):**
 - deye-inverter-mqtt version: 2024.04.2

**Comment by kbialek** [comment]
Please provide the config and full debug log. Actually MQTT reconnect is already in place. It's performed by the underlying `paho-mqtt` library, and is also tested in `tests/deye_mqtt_inttest.py`

**Comment by c0ldtech** [comment]
How can I generate the debug log? By config you mean the deye docker container config, right?

**Comment by c0ldtech** [comment]
OK, here goes - this is my docker compose config:
```

  deye-mqtt:
    container_name: deye-mqtt
    image: ghcr.io/kbialek/deye-inverter-mqtt
    environment:
      - TZ=Europe/Berlin
      - DEYE_LOGGER_IP_ADDRESS=192.168.188.47
      - DEYE_LOGGER_PORT=8899
      - DEYE_LOGGER_SERIAL_NUMBER=2756771583
      - MQTT_HOST=192.168.15.4
      - MQTT_PORT=1883
      - MQTT_USERNAME=mqttoelzsch
      - MQTT_PASSWORD=77dfjkhg55
      - DEYE_DATA_READ_INTERVAL=15
      - DEYE_PUBLISH_ON_CHANGE=true
      - DEYE_METRIC_GROUPS=deye_sg04lp3,deye_sg04lp3_battery,settings
      - DEYE_FEATURE_TIME_OF_USE=true
    
    restart: unless-stopped
    networks:
      hostPublicUtil:
        ipv4_address: 192.168.15.21
    dns:
      - 192.168.10.53
      - 192.168.15.53

```

I'll attach the log. It seems it tries to publish when the broker is stopped and fails. Judging by the log it even reeastablishes the connection to the broker, but for some reason does not publish anymore.

[_deye-mqtt_logs.txt](https://github.com/kbialek/deye-inverter-mqtt/files/15049706/_deye-mqtt_logs.txt)
